name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag suumiizxc0519/kcloudb2image:$(date +%s)
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: suumiizxc0519
        password: Mongol123zxc
    
    - name: Push Docker image to Docker Hub
      run: docker push suumiizxc0519/kcloudb2image:$(date +%s)
