name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build and push Docker image
      - name: Set current date as image tag
        id: current_date
        run: echo "::set-output name=IMAGE_TAG::$(date +%s)"

      - name: Build the Docker image
        run: |
          IMAGE_TAG=${{ steps.current_date.outputs.IMAGE_TAG }}
          docker build --file Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}/kcloudb2image:${IMAGE_TAG}" .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_TAG=${{ steps.current_date.outputs.IMAGE_TAG }}
          docker push "${{ secrets.DOCKER_USERNAME }}/kcloudb2image:${IMAGE_TAG}"

      # Deploy stack using Docker Compose via SSH
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KCLOUD_HOST }}
          username: ${{ secrets.KCLOUD_USER }}
          password: ${{ secrets.KCLOUD_PASSWORD }}
          port: ${{ secrets.KCLOUD_PORT }}
          script: |
            cd ${{ secrets.APP_PATH }}
            echo "${{ secrets.KCLOUD_PASSWORD }}" | sudo ./generate-compose.sh "${{ steps.current_date.outputs.IMAGE_TAG }}"
            # Add more deployment steps as needed
