name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build and push Docker image
      - name: Set current date as image tag
        id: current_date
        run: echo "::set-output name=IMAGE_TAG::$(date +%s)"

      - name: Build the Docker image
        run: |
          IMAGE_TAG=${{ steps.current_date.outputs.IMAGE_TAG }}
          docker build --file Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}/kcloudb2image:${IMAGE_TAG}" .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_TAG=${{ steps.current_date.outputs.IMAGE_TAG }}
          docker push "${{ secrets.DOCKER_USERNAME }}/kcloudb2image:${IMAGE_TAG}"

      # Install sshpass
      - name: Install sshpass
        run: sudo apt update && sudo apt install -y sshpass

      # Deploy stack using Docker Compose via SSH
      - name: Deploy to server
        run: |
          sshpass -p '${{ secrets.KCLOUD_PASSWORD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.KCLOUD_USER }}@${{ secrets.KCLOUD_HOST }} <<'ENDSSH'
          cd ${{ secrets.APP_PATH }}
          mkdir test
          # git pull
          # docker stop ${{ secrets.APP_NAME }}
          # docker system prune -f
          # export ${{ secrets.API_KEY_NAME }}=${{ secrets.API_KEY }}
          # make deploy_headless
          ENDSSH
