name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set current date as image tag
      run: |
        export CURRENT_DATE=$(date +%s)
        echo "::set-env name=IMAGE_TAG::$CURRENT_DATE"
    - name: Build the Docker image
      run: |
        docker build --file Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}/kcloudb2image:${{ env.IMAGE_TAG }}" .
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.DOCKER_USERNAME }}/kcloudb2image:${{ env.IMAGE_TAG }}"
