name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  print-date:
      runs-on: ubuntu-latest
      steps:
        - name: Print current date
          run: echo "Current date is $(date)"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag suumiizxc0519/kcloudb2image:v1.0.0
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: suumiizxc0519
        password: Mongol123zxc
    
    - name: Push Docker image to Docker Hub
      run: docker push suumiizxc0519/kcloudb2image:v1.0.0
